FROM python:3.9-slim
WORKDIR /app
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
COPY requirements.txt .
COPY ./backend/src/sender.py .
COPY ./backend/data/packages_with_continents.csv .
RUN pip install -r requirements.txt
CMD ["python", "sender.py"]